---
- name: "9.2.2 | Ensure 'Windows Firewall: Private: Inbound connections' is set to 'Block (default)'"
  ansible.windows.win_reg_stat:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: DefaultInboundAction
  register: output

- name: "9.2.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "9.2.2"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
