- name: PRELIM | Retrieve Default NTUSER and All Local User Hive Data
  block:
      - name: PRELIM | Load Default User Hive (Account That All New Users Get Created From Profile)
        ansible.windows.win_shell: REG LOAD HKU\DEFAULT C:\Users\Default\NTUSER.DAT
        changed_when: false
        failed_when: false

      - name: PRELIM | Pull All Username and SIDs
        ansible.windows.win_shell: Get-CimInstance -Class Win32_UserAccount -Filter "SID LIKE 'S-1-5-%'" | ForEach-Object { $_.Name + " " + $_.SID }
        changed_when: false
        failed_when: false
        register: all_users

      - name: PRELIM | Create Results List Fact For Username And SIDs
        ansible.builtin.set_fact:
            username_and_sid_results_list: "{{ all_users.stdout_lines | map('split', ' ') | list }}"

      - name: PRELIM | Load All User Hives From Username And SIDs List
        ansible.windows.win_shell: REG LOAD HKU\{{ item.1 }} C:\Users\{{ item.0 }}\NTUSER.DAT
        changed_when: false
        failed_when: false
        loop: "{{ username_and_sid_results_list }}"

      - name: PRELIM | Retrieve Current Users SIDs from HKEY_USERS
        ansible.windows.win_shell: (Get-ChildItem "REGISTRY::HKEY_USERS").name | Where-Object {$_ -notlike "*_classes"}
        changed_when: false
        failed_when: false
        register: current_users_loaded_hku
      - name: PRELIM | Create List Fact For Current Users SIDs from HKEY_USERS
        ansible.builtin.set_fact:
            hku_loaded_list: "{{ current_users_loaded_hku.stdout | regex_replace('HKEY_USERS\\\\','') | split }}"