---
- name: "19.7.26.1 | Ensure Prevent users from sharing files within their profile. is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKU:\{{ item }}\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: NoInplaceSharing
  loop: "{{ hku_loaded_list }}"
  register: output

- name: "19.7.26.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "19.7.26.1"
    compliance_status: >-
      {{
        'Compliant'
        if output.results | map(attribute='value') | select('equalto', 1) | list | length == output.results | length
        else 'Not Compliant'
      }}