---
- name: "19.7.8.1 | Ensure Configure Windows spotlight on lock screen is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
    name: ConfigureWindowsSpotlight
  loop: "{{ hku_loaded_list }}"
  register: output

- name: "19.7.8.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "19.7.8.1"
    compliance_status: >-
      {{
        'Compliant'
        if output.results | map(attribute='value') | select('equalto', 2) | list | length == output.results | length
        else 'Not Compliant'
      }}