---
- name: "19.5.1.1 | Ensure Turn off toast notifications on the lock screen is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
    name: NoToastApplicationNotificationOnLockScreen
  loop: "{{ hku_loaded_list }}"
  register: output

- name: "19.5.1.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "19.5.1.1"
    compliance_status: >-
      {{
        'Compliant'
        if output.results | map(attribute='value') | select('equalto', 1) | list | length == output.results | length
        else 'Not Compliant'
      }}