---
- name: "18.4.1 | Ensure Apply UAC restrictions to local accounts on network logons is set to Enabled MS only | Member Server"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
    name: LocalAccountTokenFilterPolicy
  register: output

- name: "18.4.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.4.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
