---
- name: "18.10.92.4.2 | Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days'"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: DeferFeatureUpdatesPeriodInDays
  register: output

- name: "18.10.92.4.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.92.4.2"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value >= 180 else 'Not Compliant' }}"
