---
- name: "18.10.57.1 | Ensure Prevent downloading of enclosures is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Feeds
    name: DisableEnclosureDownload
  register: output

- name: "18.10.57.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.57.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
