---
- name: "18.10.42.13.3 | Ensure Turn on e-mail scanning is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DisableEmailScanning
  register: output

- name: "18.10.42.13.3 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.42.13.3"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
