---
- name: "18.4.5 | Ensure Enable Structured Exception Handling Overwrite Protection SEHOP is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel
    name: DisableExceptionChainValidation
  register: output

- name: "18.4.5 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.4.5"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
