---
- name: "18.10.42.10.3 | Ensure Turn on behavior monitoring is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableBehaviorMonitoring
  register: output

- name: "18.10.42.10.3 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.42.10.3"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
