---
- name: "18.10.7.2 | Ensure Set the default behavior for AutoRun is set to Enabled Do not execute any autorun commands"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: NoAutorun
  register: output

- name: "18.10.7.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.7.2"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
