---
- name: "18.9.20.1.5 | Ensure Turn off Internet download for Web publishing and online ordering wizards is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: NoWebServices
  register: output

- name: "18.9.20.1.5 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.9.20.1.5"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
