---
- name: "18.9.19.3 | Ensure Configure registry policy processing Process even if the Group Policy objects have not changed is set to Enabled TRUE"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378Eac-683F-11D2-A89A-00C04Fbbcfa2}
    name: NoGPOListChanges
  register: output

- name: "18.9.19.3 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.9.19.3"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
