---
- name: "18.10.14.2 | Ensure Enumerate administrator accounts on elevation is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Credui
    name: EnumerateAdministrators
  register: output

- name: "18.10.14.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.14.2"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
