---
- name: "18.9.51.1.1 | PATCH | Ensure Enable Windows NTP Client is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpclient
    name: Enabled
  register: output

- name: "18.9.51.1.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.9.51.1.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
