---
- name: "18.6.4.1 | Ensure Configure DNS over HTTPS (DoH) name resolution is set to Enabled: Allow DoH or higher"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient
    name: DoHPolicy
  register: output

- name: "18.6.4.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.6.4.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and (output.value == 2 or output.value == 3) else 'Not Compliant' }}"
