---
- name: "18.10.13.1 | Ensure Require pin for pairing is set to Enabled First Time OR Enabled Always"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Connect
    name: RequirePinForPairing
  register: output

- name: "18.10.13.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.13.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and (output.value == 1 or output.value == 2) else 'Not Compliant' }}"
