---
- name: "18.9.20.1.1 | Ensure Turn off downloading of print drivers over HTTP is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Printers
    name: DisableWebPnPDownload
  register: output

- name: "18.9.20.1.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.9.20.1.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
