---
- name: "18.4.4 | Ensure Configure SMB v1 server is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
    name: SMB1
  register: output

- name: "18.4.4 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.4.4"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
