---
- name: "18.7.10 | Ensure Point and Print Restrictions When installing drivers for a new connection is set to Enabled Show warning and elevation prompt"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint
    name: NoWarningNoElevationOnInstall
  register: output

- name: "18.7.10 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.7.10"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
