---
- name: "18.1.3 | Ensure Allow Online Tips is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: AllowOnlineTips
  register: output

- name: "18.1.3 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.1.3"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
