---
- name: "18.10.79.2 | Ensure Allow Windows Ink Workspace is set to Enabled On but disallow access above lock OR Disabled but not Enabled On"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace
    name: AllowWindowsInkWorkspace
  register: output

- name: "18.10.79.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.79.2"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
