---
- name: "18.10.15.4 | Ensure Do not show feedback notifications is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\Datacollection
    name: DoNotShowFeedbackNotifications
  register: output

- name: "18.10.15.4 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.15.4"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
