---
- name: "18.9.25.1 | Ensure Allow Custom SSPs and APs to be loaded into LSASS' is set to 'Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: AllowCustomSSPsAPs
  register: output

- name: "18.9.25.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.9.25.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
