---
- name: "18.10.15.1 | Ensure Allow Diagnostic Data is set to Enabled: Diagnostic data off (not recommended) or Enabled: Send required diagnostic data"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection
    name: AllowTelemetry
  register: output

- name: "18.10.15.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.15.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and (output.value == 0 or output.value == 1) else 'Not Compliant' }}"
