---
- name: "18.10.28.4 | Ensure Turn off shell protocol protected mode is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
    name: PreXPSP2ShellProtocolBehavior
  register: output

- name: "18.10.28.4 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.28.4"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
