---
- name: "18.10.75.2.1 | Ensure Configure Windows Defender SmartScreen is set to Enabled Warn and prevent bypass"
  block:
  - name: "18.10.75.2.1 | EnableSmartScreen"
    ansible.windows.win_reg_stat:
      path: HKLM:\Software\Policies\Microsoft\Windows\System
      name: EnableSmartScreen
    register: output1

  - name: "18.10.75.2.1 | ShellSmartScreenLevel"
    ansible.windows.win_reg_stat:
      path: HKLM:\Software\Policies\Microsoft\Windows\System
      name: ShellSmartScreenLevel
    register: output2

  - name: "18.10.75.2.1 | Log compliance status"
    tags:
      - log_compliance
    set_fact:
      section_number: "18.10.75.2.1"
      compliance_status: "{{ 'Compliant' if output1.value is defined and output2.value is defined and output1.value == 1 and output2.value == 'Block' else 'Not Compliant' }}"
