---
- name: "18.7.6 | Ensure Configure RPC listener settings Authentication protocol to use for incoming RPC connections is set to Enabled Negotiate or higher"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\RPC
    name: ForceKerberosForRpc
  register: output

- name: "18.7.6 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.7.6"
    compliance_status: "{{ 'Compliant' if output.value is defined and (output.value == 0 or output.value == 1) else 'Not Compliant' }}"
