---
- name: "18.10.42.7.1 | Ensure Enable file hash computation feature is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\MpEngine
    name: EnableFileHashComputation
  register: output

- name: "18.10.42.7.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.42.7.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
