---
- name: "18.10.7.1 | Ensure Disallow Autoplay for non-volume devices is set to Enabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
    name: NoAutoplayfornonVolume
  register: output

- name: "18.10.7.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.7.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"
