---
- name: "18.10.17.4 | Ensure Enable App Installer ms-appinstaller protocol is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\AppInstaller
    name: EnableMSAppInstallerProtocol
  register: output

- name: "18.10.17.4 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.17.4"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
