---
- name: "18.10.58.3 | Ensure Allow indexing of encrypted files is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
    name: AllowIndexingEncryptedStoresOrItems
  register: output

- name: "18.10.58.3 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.58.3"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
