---
- name: "18.10.17.2 | Ensure Enable App Installer Experimental Features is set to Disabled"
  ansible.windows.win_reg_stat:
    path: HKLM:\Software\Policies\Microsoft\Windows\AppInstaller
    name: EnableExperimentalFeatures
  register: output

- name: "18.10.17.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "18.10.17.2"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 0 else 'Not Compliant' }}"
