---
- name: "2.3.7.8 | Ensure 'Interactive logon: Require Domain Controller Authentication to unlock workstation' is set to 'Enabled'"
  ansible.windows.win_reg_stat:
    path: 'HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon'
    name: ForceUnlockLogon
  register: output

- name: "2.3.7.8 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.3.7.8"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"