---
- name: 2.2.36 | Ensure 'Lock pages in memory' is set to 'No One'
  read_secpol:
    key: SeLockMemoryPrivilege  
  register: output  

- name: "2.2.36 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.2.36"
    compliance_status: "{{ 'Compliant' if output.value is not defined or output.value == 'VARIABLE IS NOT DEFINED!' else 'Not Compliant' }}"