---
- name: "2.3.11.1 | Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled'"
  ansible.windows.win_reg_stat:
    path: HKLM:\System\Currentcontrolset\Control\Lsa
    name: UseMachineId
  register: output

- name: "2.3.11.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.3.11.1"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 1 else 'Not Compliant' }}"