---
- name: "2.3.11.13 | Ensure 'Network security: Restrict NTLM: Outgoing NTLM traffic to remote servers' is set to 'Audit all' or higher"
  ansible.windows.win_reg_stat:
    path: HKLM:\System\Currentcontrolset\Control\Lsa\Msv1_0
    name: RestrictSendingNTLMTraffic
  register: output

- name: "2.3.11.13 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.3.11.13"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == 2 else 'Not Compliant' }}"