---
- name: 2.2.49 | Ensure 'Take ownership of files or other objects' is set to 'Administrators'
  read_secpol:
    key: SeTakeOwnershipPrivilege   
  register: output

- name: "2.2.49 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.2.49"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == '*S-1-5-32-544' else 'Not Compliant' }}"