---
- name: "2.3.10.9 | Configure 'Network access: Remotely accessible registry paths and sub-paths' is configured"
  ansible.windows.win_reg_stat:
    path: 'HKLM:\System\Currentcontrolset\Control\Securepipeservers\Winreg\Allowedpaths'
    name: "Machine"
  register: output

- name: "2.3.10.9 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.3.10.9"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == ['System\\CurrentControlSet\\Control\\Print\\Printers', 'System\\CurrentControlSet\\Services\\Eventlog', 'Software\\Microsoft\\OLAP Server', 'Software\\Microsoft\\Windows NT\\CurrentVersion\\Print', 'Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows', 'System\\CurrentControlSet\\Control\\ContentIndex', 'System\\CurrentControlSet\\Control\\Terminal Server', 'System\\CurrentControlSet\\Control\\Terminal Server\\UserConfig', 'System\\CurrentControlSet\\Control\\Terminal Server\\DefaultUserConfiguration', 'Software\\Microsoft\\Windows NT\\CurrentVersion\\Perflib', 'System\\CurrentControlSet\\Services\\WINS', 'System\\CurrentControlSet\\Services\\CertSvc', 'System\\CurrentControlSet\\Services\\SysmonLog'] else 'Not Compliant' }}"