---
- name: 2.2.46 | Ensure 'Restore files and directories' is set to 'Administrators'
  read_secpol:
    key: SeRestorePrivilege   
  register: output

- name: "2.2.46 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.2.46"
    compliance_status: "{{ 'Compliant' if output.value is defined and output.value == '*S-1-5-32-544' else 'Not Compliant' }}"