---
- name: 2.2.35 | Ensure 'Load and unload device drivers' is set to 'Administrators'
  read_secpol:
    key: SeLoadDriverPrivilege   
  register: output

- name: "2.2.35 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "2.2.35"
    compliance_status: "{{ 'Compliant' if output.value == '*S-1-5-32-544' else 'Not Compliant' }}"