- name: "17.6.1 | Ensure Audit Detailed File Share is set to include Failure"
  block:
      - name: "17.6.1 | AUDIT | Get current audit events."
        ansible.windows.win_shell: AuditPol /get /subcategory:"Detailed File Share" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
        changed_when: false
        failed_when: false
        check_mode: false
        register: output

- name: "17.6.1 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "17.6.1"
    compliance_status: "{{ 'Compliant' if 'Failure' in output.stdout else 'Not Compliant' }}"