- name: "17.6.2 | Ensure Audit File Share is set to Success and Failure"
  block:
      - name: "17.6.2 | AUDIT | Get current audit events."
        ansible.windows.win_shell: AuditPol /get /subcategory:"File Share" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
        changed_when: false
        failed_when: false
        check_mode: false
        register: output

- name: "17.6.2 | Log compliance status"
  tags:
    - log_compliance
  set_fact:
    section_number: "17.6.2"
    compliance_status: "{{ 'Compliant' if 'Success' in output.stdout and 'Failure' in output.stdout else 'Not Compliant' }}"